---
- name: Copy bashrc to the user home directory
  template:
    src:  bashrc.j2
    dest: "{{item.HomeDir | default('/home/' + item.UserName)}}/.bashrc"
    owner:  "{{item.UserName}}"
    group:  "{{item.PrimaryGroup| default('users')}}"
    backup: no
    mode: 0644
  with_items: "{{DotFiles}}"
  loop_control:
    label: "{{item.UserName}}"  