---
- name: Converge
  hosts: all
  gather_facts: yes
  become: true
  environment:
     GIT_SSL_NO_VERIFY: 'true'

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 43200   # 12 hours

    - name: Make sure git is installed
      ansible.builtin.apt: 
        name: git 
        state: present

    - name: Create test user
      ansible.builtin.user:
        name: testuser
        create_home: yes
        comment: testuser
        group: users
        shell: /bin/bash
        state: present
  roles:
    - role: jcpetro97.dotfiles
      vars:
        DotFiles:
          - UserName: "testuser"
          - UserName: "root"