---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    test_user: "test_usr"
    test_home: "/home/test_usr"

  tasks:
    - name: "Verify | Check if .vimrc symlink exists"
      ansible.builtin.stat:
        path: "{{ test_home }}/.vimrc"
      register: vimrc_stat

    - name: "Verify | Assert .vimrc is a link to .dotfiles"
      ansible.builtin.assert:
        that:
          - vimrc_stat.stat.exists
          - vimrc_stat.stat.islnk
          - vimrc_stat.stat.lnk_target == test_home + '/.dotfiles/.vimrc'

    - name: "Verify | Check if .bashrc symlink exists"
      ansible.builtin.stat:
        path: "{{ test_home }}/.bashrc"
      register: bashrc_stat

    - name: "Verify | Assert .bashrc is a link to .dotfiles"
      ansible.builtin.assert:
        that:
          - bashrc_stat.stat.exists
          - bashrc_stat.stat.islnk
          - bashrc_stat.stat.lnk_target == test_home + '/.dotfiles/.bashrc'

    - name: "Verify | Check if aliases_common symlink exists"
      ansible.builtin.stat:
        path: "{{ test_home }}/.aliases/aliases_common"
      register: alias_stat

# # DEBUG TASK: This will print the actual target so we can see the mismatch
#     - name: "DEBUG | Show aliases_common link target"
#       ansible.builtin.debug:
#         msg: 
#           - "Expected Target: {{ test_home }}/.dotfiles/aliases_common"
#           - "Actual Target:   {{ alias_stat.stat.lnk_target }}"
#       when: alias_stat.stat.exists and alias_stat.stat.islnk

    - name: "Verify | Assert aliases_common is a link"
      ansible.builtin.assert:
        that:
          - alias_stat.stat.exists
          - alias_stat.stat.islnk
          - alias_stat.stat.lnk_target == test_home + '/.dotfiles/.aliases/aliases_common'

    - name: "Verify | Check if aliases_extra symlink exists"
      ansible.builtin.stat:
        path: "{{ test_home }}/.aliases/aliases_extra"
      register: extra_stat

    - name: "Verify | Assert aliases_extra is a link"
      ansible.builtin.assert:
        that:
          - extra_stat.stat.exists
          - extra_stat.stat.islnk